# Generated by Django 3.0.4 on 2020-04-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slugapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
